### ISSUE TITLE
Context access might be invalid: strategy

### ISSUE THREAD

**Issue by brianjmurrell** [github/vscode-github-actions#113]
**Describe the bug**
Many invalid instances of **Context access might be invalid** throughout a workflow file.

**To Reproduce**
1. Create a workflow with a job:
```
jobs:
  dump_contexts_to_log:
    runs-on: [self-hosted, light]
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Dump vars context
        run: echo '${{ toJSON(vars) }}'
```

**Expected behavior**
Such a job successfully dumps contexts such as `strategy` yet the this plugin is flagging it as _might be invalid_.

**Extension Version**
`v0.25.4`

**Additional context**
I have 21 of these types of warnings and not a single one of them is accurate.  This is very distracting when trying to resolve legitimate issues in one's workflow file(s).

**Comment by KetchupOnMyKetchup** [comment]
@brianjmurrell Could you please also include a screenshot of where the warnings are specifically? Thanks!

**Comment by elbrenn** [comment]
Thanks, we were trying to verify which contexts were being highlighted as warning. Looks like both the strategy and matrix contexts aren't being recognized within steps

Here is a repro:
<img width="293" alt="Screenshot 2023-04-13 at 4 59 57 PM" src="https://github.com/github/vscode-github-actions/assets/34719884/94a4a169-f4fa-41f9-be4d-08ba1e955cc8">

Initial observations:

Hovering over `run` shows strategy and matrix as supported contexts, so the error highlighting is unexpected.
<img width="602" alt="Screenshot 2023-04-13 at 5 04 03 PM" src="https://github.com/github/vscode-github-actions/assets/34719884/0b8d6e17-1885-4061-b42c-ea1d3e4d4ffe">
 
Possibly a bug propagating context to the value for the run key

**Comment by migmit** [comment]
Have the same problem with v.0.25.7

**Comment by G-Ke** [comment]
I saw this as well. Restarting VSCode resolved the issue at least once for me.

**Comment by luis-guimaraes-exoawk** [comment]
I have the same problem with `secrets` context

**Comment by kjeldahl** [comment]
> I have the same problem with `secrets` context

I did too, but a restart solved it. At least once, as @G-Ke said :-)

**Comment by jsoref** [comment]
```yaml
jobs:
  #...
  update:
    strategy:
      fail-fast: false
      matrix:
        category:
        #...
        - tests
    name: Update PR (${{matrix.category}})
    if: ${{
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        contains(github.event.comment.body, matrix.category) &&
        contains(github.event.comment.body, '@check-spelling-bot apply')
      }}
```
<img width="583" alt="image" src="https://github.com/github/vscode-github-actions/assets/2119212/6ff2c171-c08f-499f-82a1-067e04c1c4b7">

Note that the use of `${{...}}` in the `if:` is partially to work around #60...

https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability

Workflow key | Context | Special functions
-- | -- | --
jobs.<job_id>.steps.if | github, needs, strategy, matrix, job, runner, env, vars, steps, inputs | always, cancelled, success, failure, hashFiles

---

Fwiw, the addon might support GHES3.5, and if so, it should really have a way to let users tell it that we don't care about GHES3.5..GHES3.9 and only care about GitHub.com

But, here's the docs for 3.5:
https://docs.github.com/en/enterprise-server@3.5/actions/learn-github-actions/contexts#context-availability
,
Workflow key | Context | Special functions
-- | -- | --
jobs.<job_id>.steps.if | github, needs, strategy, matrix, job, runner, env, steps, inputs | always, cancelled, success, failure, hashFiles

Please also note that the available function list includes `hashFiles` which the add-on isn't offering either.

**Comment by adambirds** [comment]
Is there a fix for this yet as it is really annoying having all these errors when it isn't an issue.

**Comment by jsoref** [comment]
@BertelBB https://github.com/github/vscode-github-actions/issues/113#issuecomment-1572081368 is a different problem, this ticket is specifically about `strategy` which is fairly new. How you set `env` context properties will vary and it wouldn't shock me if this add-on can't handle them, but the fix would be very different.

**Comment by ericsciple** [comment]
This fix is released now. Update the VSCode extension to get the latest fix.

**Comment by MilanObrenovicNeumo** [comment]
> This fix is released now. Update the VSCode extension to get the latest fix.

Not fixed.

<img width="1337" height="217" alt="Image" src="https://github.com/user-attachments/assets/74993e91-cca2-4ce8-b612-b53427c16129" />

<img width="1762" height="591" alt="Image" src="https://github.com/user-attachments/assets/968c3f27-aaab-4904-9ef0-d81d3156cc0d" />

**Comment by jsoref** [comment]
@MilanObrenovicNeumo this ticket is *only* for *strategy*, it isn't a generic ticket.

**Comment by MilanObrenovicNeumo** [comment]
> [@MilanObrenovicNeumo](https://github.com/MilanObrenovicNeumo) this ticket is _only_ for _strategy_, it isn't a generic ticket.

Then why mention the fix was released and to update the vscode extension?
That would imply the fix is released for generic problem.

As a temporary solution, how is this properly fixed?
The only way i could think of is something like:

```
${{ steps.extract_environment.outputs }}
```

Instead of

```
${{ env.ENVIRONMENT }}
```
