### ISSUE TITLE
Cannot fetch github context

### ISSUE THREAD

**Issue by haimat** [github/vscode-github-actions#55]
**Describe the bug**
After installing the GitHub Actions extension, I log in to GitHub within VS Code using the browser. However, even though I am logged-in (which I know because the GitHub Co-Pilot extension is working fine), VS Code tells me it cannot use the new GitHub Actions extension. I can see the following error in the output console:

```text
Error: Cannot fetch github context
    at po (/home/mfb/.vscode/extensions/github.vscode-github-actions-0.25.3/dist/extension-node.js:2:1596092)
    at /home/mfb/.vscode/extensions/github.vscode-github-actions-0.25.3/dist/extension-node.js:2:1631727
    at Ss (/home/mfb/.vscode/extensions/github.vscode-github-actions-0.25.3/dist/extension-node.js:2:1631683)
    at f.n (/snap/code/122/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6818)
    at f.m (/snap/code/122/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6781)
    at f.l (/snap/code/122/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6238)
```

**Extension Version**
`0.25.0`

**Additional context**
I am working under Ubuntu Linux 22.04, if that matters.

**Comment by catramsden** [comment]
I had the same issue (on windows), resolved by disabling the extension, reloading vscode and then re-enabling it. 

I now see the following in the output:
`
Activating GitHub Actions extension...
...initialized
`

**Comment by KetchupOnMyKetchup** [comment]
This should be fixed in the newly released version 0.25.4

**Comment by Eazash** [comment]
The error still persists on version _0.25.4_. The error message I'm getting is a little different though
```
Activating GitHub Actions extension...

Cannot fetch github context
Error: Cannot fetch github context
	at Ao (/home/ezra/.vscode/extensions/github.vscode-github-actions-0.25.4/dist/extension-node.js:2:1597413)
	at async /home/ezra/.vscode/extensions/github.vscode-github-actions-0.25.4/dist/extension-node.js:2:1623054
	at async Rs (/home/ezra/.vscode/extensions/github.vscode-github-actions-0.25.4/dist/extension-node.js:2:1622125)
	at async E.n (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6646)
	at async E.m (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6609)
	at async E.l (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6066)

Cannot fetch github context
Error: Cannot fetch github context
	at Ao (/home/ezra/.vscode/extensions/github.vscode-github-actions-0.25.4/dist/extension-node.js:2:1597413)
	at async /home/ezra/.vscode/extensions/github.vscode-github-actions-0.25.4/dist/extension-node.js:2:1633563
	at async Rs (/home/ezra/.vscode/extensions/github.vscode-github-actions-0.25.4/dist/extension-node.js:2:1633519)
	at async E.n (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6646)
	at async E.m (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6609)
	at async E.l (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6066)
...initialized
```

**Comment by Eazash** [comment]
Oh and I'm on archlinux. It seems to be relevant as the error is not present on windows while using version _0.25.4_

**Comment by KetchupOnMyKetchup** [comment]
@Eazash - 

Just to confirm:
- Are you using VS Code on your local machine with archlinux?
- Or, are you using VS Code in the browser on vscode.dev or github.dev?

If you are using VS Code on your local machine, could you please try these and let me know if any of them help?
1. Could you disable your other VS Code extensions temporarily to see if they are causing an issue?
2. Once you login, can you try to reload the window?
  ![image](https://github.com/github/vscode-github-actions/assets/7976517/dc45a941-26b5-48bc-b16e-63d99f38c141)
3. Do you have multiple repos or any GitHub Wiki repos open?

**Comment by KetchupOnMyKetchup** [comment]
@Eazash - Thank you for sending that and for confirming that it works now with the uninstall and reinstall and you can't repro the bug! I'll keep in mind this error in case we see another similar one, I appreciate your help debugging this!!!

**Comment by KetchupOnMyKetchup** [comment]
@haimat - Unfortunately we don't support the browser version (1vscode.dev` and `github.dev`) currently, though we'd like to in the future when we get more bandwidth. 

Could you please use VS Code on your local machine in order to use the extension now? Do you have any problems with this workflow?

Thanks!

**Comment by haimat** [comment]
> @haimat - Unfortunately we don't support the browser version (`vscode.dev` and `github.dev`) currently, though we'd like to in the future when we get more bandwidth. We are currently trying to get the local VS Code extension version as stable and bug free as possible before we continue supporting remote repositories.
> 
> Could you please use VS Code on your local machine in order to use the extension now? Do you have any problems with this workflow?

@KetchupOnMyKetchup Thanks for your response, but I don't use the browser version of VS Code, I work with the installed version on Ubuntu.

**Comment by KetchupOnMyKetchup** [comment]
@haimat  - I just tried this in WSL Ubuntu 22.04 and it worked for me, here is a demo of that specific environment:
![vscodewsldemo](https://github.com/github/vscode-github-actions/assets/7976517/503973b8-016a-4756-85f0-0e4ab4ecbbcf)

We fixed some bugs in the new version `v0.25.4` and one that we noticed was a login issue and I am hoping it addressed this issue, but if not would be happy to work on this if I can get a specific error or if I can repro it on my side. 

Would you please try these to see if any of them fix your issue:
1. Uninstall `v0.25.3` and install the new version `v0.25.4` and login
2. Try reloading VS Code
  ![image](https://github.com/github/vscode-github-actions/assets/7976517/5606a15a-482e-4192-8822-8d2ef96c42bd)
3. Try disabling any other extensions to see if they are interfering. Then reload VS Code.
4. Do you have any Wiki repos in your GitHub repo? If so these could be the issue and we should make a bug for this. 
5. Lastly, could you check the Output tab in VS Code and select GitHub Actions in the dropdown?  Could you send us a copy of any errors there if they are different than the original ones that you sent at the top?
  ![image](https://github.com/github/vscode-github-actions/assets/7976517/e1ca53ac-cbb4-4be2-985c-f32698081185)

Please let me know if any of these steps work, if so which one. And if not, what error messages you have so I can debug. Thank you so much for your help!

**Comment by haimat** [comment]
@KetchupOnMyKetchup Thanks, after re-installing this extension it seems the bug has indeed been fixed. I will re-open this issue if the problem still occurs. Thanks for your help!

**Comment by iugo** [comment]
github.vscode-github-actions 0.31.0 (macOS VSCode)

```
Cannot fetch github context
Error: Cannot fetch github context
	at De (/Users/username/.vscode-insiders/extensions/github.vscode-github-actions-0.31.0/dist/extension-node.js:1:1153509)
	at async /Users/username/.vscode-insiders/extensions/github.vscode-github-actions-0.31.0/dist/extension-node.js:1:1340171
	at async dg._executeContributedCommand (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:494:48675)
```
