### ISSUE TITLE
Unable to connect to the GitHub API , Please check your internet connection. Installed in WSL

### ISSUE THREAD

**Issue by 0lzi** [github/vscode-github-actions#57]
**Describe the bug**
After installing this in WSL and logging in I receive the below message.

 

**To Reproduce**
1. Install extension in WSL workspace
2. Login to Github and authorise with org
3. See error

**Expected behavior**
1. Install extension in WSL workspace
2. Login to Github and authorise with org
3. It Works as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/4409144/228493327-e6718320-590a-49fb-ae29-7e26ae099a7b.png)

**Extension Version**
v0.25.3

**Additional context**

**Comment by briantist** [comment]
I have the same issue. When I click `Refresh` I get no error, only this message:

![image](https://user-images.githubusercontent.com/1260690/228554456-328d0184-46bb-4f1b-8b7a-ae165c8be453.png)

**Comment by areifert** [comment]
Clicking on the Refresh button (in the GitHub Actions tab) does nothing for me either. Checking the developer console in VS Code, I'm seeing the following error:

```
ERR command 'github-actions.explorer.refresh' not found: Error: command 'github-actions.explorer.refresh' not found
    at v.k (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1552:2618)
    at v.executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1552:2534)
    at async i.open (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:615:42187)
    at async h.open (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:615:43698)
```

**Comment by KetchupOnMyKetchup** [comment]
I am investigating this bug now and was able to repro.

There are a couple of workarounds for now that worked for me using WSL Ubuntu 22.04 that you can try for now while I investigate:
1. Login to VS Code on Windows without connecting to WSL first, then connect to WSL
1. Login, see the failure, reload VS Code (Ctrl + Shift + P, then type in `Developer: Reload Window`)
![wslloginreload](https://user-images.githubusercontent.com/7976517/230437901-26d94b4c-6bc5-40be-b402-739acc7faac1.gif)

**Comment by areifert** [comment]
I'm actually seeing this bug on a (M1) Mac rather than Windows. It seems to not be installing at all. The VS Code developer console shows the following after attempting to uninstall and reinstall the plugin:
```
Activating extension 'github.vscode-github-actions' failed: Not Found.
```

**Comment by KetchupOnMyKetchup** [comment]
This should be fixed in the newly released version 0.25.4

**Comment by 0lzi** [comment]
>              ](https://user-images.githubusercontent.com/7976517/230437901-26d94b4c-6bc5-40be-b402-739acc7faac1.gif)

This didnt fix it for me. It says `Unable to find a Git executable` I am guessing I would need to install Git in Windows first

![image](https://github.com/github/vscode-github-actions/assets/4409144/8d3293b7-ce6c-40f1-8f17-a8c4dd96e1d5)

**Comment by lebrice** [comment]
@KetchupOnMyKetchup  This is still happening to me in v0.26.2

**Comment by scottco-slalom** [comment]
This fixed this issue for me:
https://github.com/github/vscode-github-actions/issues/251#issuecomment-1936306267
