### ISSUE TITLE
Plugin not installing properly on M1 Mac

### ISSUE THREAD

**Issue by areifert** [github/vscode-github-actions#93]
**Describe the bug**
I'm trying to install this plugin from VS Code installed on an M1 Mac (using the built-in Extensions Marketplace). After clicking "Install", I received a prompt to authenticate via GitHub, which appears to work.

However, when navigating to the GitHub Actions tab in VS Code, I only see the message "Unable to connect to the GitHub API, please check your internet connection" along with a Refresh button. Clicking Refresh appears to have no effect.

Tried opening the Developer Console in VS Code, and am seeing the following error message:

<img width="1840" alt="Screenshot 2023-04-06 at 10 43 05" src="https://user-images.githubusercontent.com/5041769/230443175-84f3d11d-4fef-4bd8-88c7-ad0306167a03.png">

I've tried uninstalling and reinstalling the plugin several times and am still seeing this error message.

**To Reproduce**
1. Open the Extensions tab in VS Code, search for "GitHub Actions"
2. Select the GitHub Actions extensions and click Install
3. When prompted, complete GitHub authentication for this plugin
4. Navigate to the GitHub Actions tab in VS Code
5. Error message "Unable to connect to the GitHub API, please check your internet connection" is displayed. Clicking on the Refresh button has no effect.
6. Open the Developer Console (under Help > Toggle Developer Tools), error message "Activating extension 'github.vscode-github-actions' failed: Not Found." is displayed.

**Extension Version**
`v0.25.3`

**Additional context**
System: MacBook Pro 2021 (Apple M1 Pro)
OS: macOS Ventura 13.3

VS Code information:
Version: 1.77.1 (Universal)
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:23:33.779Z (1 day ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No

**Comment by KetchupOnMyKetchup** [comment]
This should be fixed in the newly released version 0.25.4.

**Comment by areifert** [comment]
I just installed the latest version of this plugin, still seeing this exact same error behavior. Please reopen this issue.

(Why was this issue closed without any opportunity for end user testing?)

**Comment by KetchupOnMyKetchup** [comment]
We'll take a look at this next week, thanks so much for letting us know! 

Sorry about that, we're currently working on determining the best workflow for us and issues can always be re-opened if it isn't resolved. If we close the issue, it's a good way to indicate that we tried to fix the issue and that there is a new release.

**Comment by areifert** [comment]
Understood, thank you for reopening this issue. Please let me know if you need any further info for troubleshooting.

**Comment by joshmgross** [comment]
I'm on an M1 Mac with the same OS version `13.3.1`:

![CleanShot 2023-04-10 at 15 48 17](https://github.com/github/vscode-github-actions/assets/16631042/ee67d808-f9cf-4a13-90b2-b9c888ec4dca)

I'm not seeing any issues installing or activating the extension.

**Comment by KetchupOnMyKetchup** [comment]
@areifert - We just tried this on an M1 Mac and didn't have any issues (see above).

Could you please try some other steps:
1. Could you check the Output tab in VS Code and select GitHub Actions in the dropdown? We suspect there could be a network issue happening. Could you send us a copy of any errors there?
  ![image](https://github.com/github/vscode-github-actions/assets/7976517/80a0f49f-94e6-4012-a483-309481122293)
1. Could you disable your other extensions temporarily to see if they are causing an issue?

**Comment by areifert** [comment]
Played around with this some more, I think I've found the root cause.

My VS Code workspace has several different Git repositories in it. I tried creating a brand new workspace and added just one Git repository, and the GitHub Actions plugin works as expected. Adding more than one Git repository also seems to work fine.

After playing around with my original workspace some more, the issue appears to be stemming from a local clone of a GitHub wiki that I have included in my workspace. After removing the directory containing my GitHub wiki, the GitHub Actions plugin works as expected.

**Comment by KetchupOnMyKetchup** [comment]
@areifert - That's great news that you were able to get it working and found out that it was related to the Wiki directory.  Could we go ahead and close this bug? We could open another one for the GitHub wiki if that's an issue that you'd like to get on the backlog.

Thank you so much for your time and help with this! 🎉

**Comment by areifert** [comment]
I could rename this issue to specify that it is related to GitHub wikis. Otherwise, we could open a separate issue and close out this one. Please let me know which you would prefer.

**Comment by KetchupOnMyKetchup** [comment]
@areifert - If it's not too much work, could we create a new one so that its less work for whoever picks it up to read? I think all the comments might be a lot to catch up on and its easier to directly state its Wikis with a clean issue then close this one. Sorry to make you create a new issue twice now! And thank you a ton!

**Comment by areifert** [comment]
Opened new issue #111
